export const allSuggestionsMock = {
  info: { count: 11, pages: 1, next: null, prev: null },
  characters: [
    {
      id: 200,
      name: "Lawyer Morty",
      status: "unknown",
      species: "Human",
      type: "",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/200.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/22"],
      url: "https://rickandmortyapi.com/api/character/200",
      created: "2017-12-30T12:49:52.971Z",
    },
    {
      id: 228,
      name: "Mohawk Guy",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Post-Apocalyptic Earth",
        url: "https://rickandmortyapi.com/api/location/8",
      },
      location: {
        name: "Post-Apocalyptic Earth",
        url: "https://rickandmortyapi.com/api/location/8",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/228.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/23"],
      url: "https://rickandmortyapi.com/api/character/228",
      created: "2017-12-30T16:10:03.881Z",
    },
    {
      id: 258,
      name: "Pawnshop Clerk",
      status: "Alive",
      species: "Alien",
      type: "",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Pawn Shop Planet",
        url: "https://rickandmortyapi.com/api/location/55",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/258.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/7"],
      url: "https://rickandmortyapi.com/api/character/258",
      created: "2017-12-31T13:30:33.611Z",
    },
    {
      id: 378,
      name: "Wall Crawling Rick",
      status: "unknown",
      species: "Humanoid",
      type: "Lizard-Person",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/378.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/22"],
      url: "https://rickandmortyapi.com/api/character/378",
      created: "2018-01-10T19:33:30.804Z",
    },
    {
      id: 399,
      name: "Tiny-persons advocacy group lawyer",
      status: "Alive",
      species: "Mythological Creature",
      type: "Giant",
      gender: "Male",
      origin: {
        name: "Giant's Town",
        url: "https://rickandmortyapi.com/api/location/14",
      },
      location: {
        name: "Giant's Town",
        url: "https://rickandmortyapi.com/api/location/14",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/399.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/5"],
      url: "https://rickandmortyapi.com/api/character/399",
      created: "2018-04-15T17:34:02.076Z",
    },
    {
      id: 438,
      name: "Michael's Lawyer",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      location: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/438.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/12"],
      url: "https://rickandmortyapi.com/api/character/438",
      created: "2018-05-01T11:57:16.266Z",
    },
    {
      id: 512,
      name: "Morty’s Lawyer",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      location: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/512.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/32"],
      url: "https://rickandmortyapi.com/api/character/512",
      created: "2020-05-02T12:25:59.290Z",
    },
    {
      id: 550,
      name: "Double Microwawe",
      status: "Alive",
      species: "Humanoid",
      type: "Cyborg",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Heist-Con",
        url: "https://rickandmortyapi.com/api/location/88",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/550.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/34"],
      url: "https://rickandmortyapi.com/api/character/550",
      created: "2020-05-07T10:07:53.077Z",
    },
    {
      id: 562,
      name: "Balthromaw",
      status: "Alive",
      species: "Mythological Creature",
      type: "Dragon",
      gender: "Male",
      origin: {
        name: "Draygon",
        url: "https://rickandmortyapi.com/api/location/94",
      },
      location: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/562.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/35"],
      url: "https://rickandmortyapi.com/api/character/562",
      created: "2020-05-07T11:32:16.357Z",
    },
    {
      id: 659,
      name: "Morty’s Father-in-law",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Near-Duplicate Reality",
        url: "https://rickandmortyapi.com/api/location/104",
      },
      location: {
        name: "Near-Duplicate Reality",
        url: "https://rickandmortyapi.com/api/location/104",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/659.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/39"],
      url: "https://rickandmortyapi.com/api/character/659",
      created: "2020-08-13T11:23:55.003Z",
    },
    {
      id: 660,
      name: "Morty’s Mother-in-law",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Female",
      origin: {
        name: "Near-Duplicate Reality",
        url: "https://rickandmortyapi.com/api/location/104",
      },
      location: {
        name: "Near-Duplicate Reality",
        url: "https://rickandmortyapi.com/api/location/104",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/660.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/39"],
      url: "https://rickandmortyapi.com/api/character/660",
      created: "2020-08-13T11:25:50.784Z",
    },
  ],
};



